#Snorkit 2017
#Version 1.0

messages:
  no-perm: "&cVous n'avez pas la permission d'effectuer cette commande"
kits:
  Default:
    items:
      - 276
      - 310
      - 311
      - 312
      - 313
      - 442